# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code Quality

on:
  pull_request:
    branches: [ "develop", "staging", "master" ]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install Dependencies
      run: yarn install
    
    - name: Check Linting
      run: yarn run lint

    - name: Run Tests
      run: yarn test --passWithNoTests
